### ISSUE TITLE
Correct Access

### ISSUE THREAD

**Issue by camipozas** [janjoswig/Ducula#4]
I want to clone the repo but says git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by janjoswig** [comment]
It is probably because you need to upload a proper ssh key on GitHub (check [this site](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account) for help).

If you do not want to use a key for authentication, consider using the HTTPS protocol when cloning instead.
